/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avltree;

import avltree.ArbolAVL;
import avltree.Visualizador;
import avltree.Recorridos;
import javax.swing.JOptionPane;
/**
 *
 * @author ikono
 */
public class treegrafico extends javax.swing.JFrame {
     ArbolAVL arbol = new ArbolAVL();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(treegrafico.class.getName());

    /**
     * Creates new form treegrafico
     */
    public treegrafico() {
        
        initComponents();
            
    jareaDibujo.setFont(new java.awt.Font(
        "Monospaced", java.awt.Font.PLAIN, 14));
    jareaInfo.setFont(new java.awt.Font(
        "Monospaced", java.awt.Font.PLAIN, 12));
    }
    
    private void actualizarPantalla() {
    // Si el árbol está vacío, muestra mensaje
    if (arbol.estaVacio()) {
        jareaDibujo.setText("\n    El arbol esta vacio.");
        jareaInfo.setText("");
        return;
    }
    // Dibuja el árbol en la primera área de texto
    String dibujo = Visualizador.obtenerArbolComoTexto(
        arbol.getRaiz(), arbol);
    jareaDibujo.setText(dibujo);

    // Estadísticas y recorridos en la segunda área
    StringBuilder sb = new StringBuilder();
    sb.append(Visualizador.obtenerEstadisticas(arbol.getRaiz(), arbol));
    sb.append("\nRECORRIDOS:\n");
    sb.append("  Inorden   : ")
      .append(Recorridos.listaAString(Recorridos.inorden(arbol.getRaiz())))
      .append("\n");
    sb.append("  Preorden  : ")
      .append(Recorridos.listaAString(Recorridos.preorden(arbol.getRaiz())))
      .append("\n");
    sb.append("  Postorden : ")
      .append(Recorridos.listaAString(Recorridos.postorden(arbol.getRaiz())))
      .append("\n");
    jareaInfo.setText(sb.toString());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jValor = new javax.swing.JLabel();
        jtxtValor = new javax.swing.JTextField();
        jInsertar = new javax.swing.JButton();
        jEliminar = new javax.swing.JButton();
        jBuscar = new javax.swing.JButton();
        jLimpiar = new javax.swing.JButton();
        jEjemplo = new javax.swing.JButton();
        jSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jareaDibujo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jareaInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jValor.setText("Valor");

        jtxtValor.setText("txtValor");

        jInsertar.setText("Insertar+");
        jInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertarActionPerformed(evt);
            }
        });

        jEliminar.setText("Eliminar");
        jEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEliminarActionPerformed(evt);
            }
        });

        jBuscar.setText("Buscar");
        jBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarActionPerformed(evt);
            }
        });

        jLimpiar.setText("Limpiar");
        jLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarActionPerformed(evt);
            }
        });

        jEjemplo.setText("Ejemplo");
        jEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEjemploActionPerformed(evt);
            }
        });

        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 115, Short.MAX_VALUE)
        );

        jareaDibujo.setColumns(20);
        jareaDibujo.setRows(5);
        jScrollPane1.setViewportView(jareaDibujo);

        jareaInfo.setColumns(20);
        jareaInfo.setRows(5);
        jScrollPane2.setViewportView(jareaInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSalir)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jValor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104)
                                    .addComponent(jInsertar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jEliminar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBuscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLimpiar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jEjemplo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2)
                                    .addGap(6, 6, 6)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jValor)
                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInsertar)
                    .addComponent(jEliminar)
                    .addComponent(jBuscar)
                    .addComponent(jLimpiar)
                    .addComponent(jEjemplo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGap(30, 30, 30)
                .addComponent(jSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertarActionPerformed
         try {
        int valor = Integer.parseInt(jtxtValor.getText().trim());
        arbol.insertar(valor);
        actualizarPantalla();
        jtxtValor.setText("");
        jtxtValor.requestFocus();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un numero entero valido.");
    }
    }//GEN-LAST:event_jInsertarActionPerformed

    private void jEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEjemploActionPerformed
         arbol = new ArbolAVL();
    int[] valores = {50, 30, 70, 20, 40, 60, 80};
    for (int v : valores) {
        arbol.insertar(v);
    }
    actualizarPantalla();
    JOptionPane.showMessageDialog(this, "Arbol de ejemplo cargado.");
    }//GEN-LAST:event_jEjemploActionPerformed

    private void jEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEliminarActionPerformed
        try {
        int valor = Integer.parseInt(jtxtValor.getText().trim());
        arbol.borrar(valor);
        actualizarPantalla();
        jtxtValor.setText("");
        jtxtValor.requestFocus();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un numero para borrar.");
    }
    }//GEN-LAST:event_jEliminarActionPerformed

    private void jBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarActionPerformed
         try {
        int valor = Integer.parseInt(jtxtValor.getText().trim());
        boolean encontrado = arbol.buscar(valor);
        if (encontrado)
            JOptionPane.showMessageDialog(this, "El valor "+valor+" SI existe en el arbol.");
        else
            JOptionPane.showMessageDialog(this, "El valor "+valor+" NO se encuentra en el arbol.");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa un numero para buscar.");
    }
    }//GEN-LAST:event_jBuscarActionPerformed

    private void jLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarActionPerformed
        arbol = new ArbolAVL();  // reinicia el árbol
    actualizarPantalla();
    jtxtValor.setText("");
    JOptionPane.showMessageDialog(this, "Arbol vaciado.");
    }//GEN-LAST:event_jLimpiarActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new treegrafico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuscar;
    private javax.swing.JButton jEjemplo;
    private javax.swing.JButton jEliminar;
    private javax.swing.JButton jInsertar;
    private javax.swing.JButton jLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jValor;
    private javax.swing.JTextArea jareaDibujo;
    private javax.swing.JTextArea jareaInfo;
    private javax.swing.JTextField jtxtValor;
    // End of variables declaration//GEN-END:variables
}
